### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by lgatto** [zhangyuqing/simulatorZ#4]
Is there a reference/paper that can be used to refer to this package, or another published material that uses `simulatorZ`? cc @lwaldron

**Comment by lwaldron** [comment]
Hi @lgatto - the package itself isn't published yet, but the method was described in this paper which you can cite in the meantime:

Bernau C, Riester M, Boulesteix A-L, Parmigiani G, Huttenhower C, Waldron L, Trippa L: Cross-study validation for the assessment of prediction algorithms. Bioinformatics 2014, 30:i105–12.

@zhangyuqing - let's submit soon!

**Comment by lgatto** [comment]
Thanks @lwaldron.

**Comment by lwaldron** [comment]
@lgatto , it occurred to me that I didn't ask what you wanted to cite it for.  The above paper describes the simulation of independent studies.  The following paper describes the plus/minus or mas-o-menos discrimination method that the rowCoxTests() function might be used for:

Zhao SD, Parmigiani G, Huttenhower C, Waldron L: Más-o-menos: a simple sign averaging method for discrimination in genomic data analysis. Bioinformatics 2014, 30:3062–3069.

**Comment by lgatto** [comment]
@lwaldron It's for a short manuscript about testing and validation of computational methods, in particular about data simulation.

**Comment by lwaldron** [comment]
@lgatto Neat!  Looking forward to seeing it in print.
